### ISSUE TITLE
Unable to resize .jpeg file

### ISSUE THREAD

**Issue by veniovinco** [nicojeske/mousewheel-image-zoom#22] opened 2023-02-28 02:47 UTC
The issue occurs since the latest update of this plugin, version 1.0.14

**Comment by nicojeske** [comment] 2023-02-28 10:32
Can you give me an example how you included the image in markdown? The plugin does not make a distinction about filetypes and on my local test setup everything seems to be working as expected.

**Comment by veniovinco** [comment] 2023-02-28 12:58
![[image1.png]] -> this can be resized
![[image2.jpeg]] -> this cannot be resized
![[image3.jpg]] -> this cannot be resized
I am pretty sure that this weird thing happens right after I update the plugin. I would try on another computer later. Can you reproduce this situation btw?

**Comment by dapaning** [comment] 2023-03-01 03:04
This also happens to me and I can't resize the image. I returned to 1.0.13 and it was fine

**Comment by nicojeske** [comment] 2023-03-01 05:17
I have confirmed that this issue can be replicated in my local environment. The issue should be addressed in the new version (1.0.15).

**Closed by nicojeske** 2023-03-01 05:17 UTC

**Comment by ku-zhen** [comment] 2023-03-09 13:26
hello，it does‘t work for the .jpg iamge either

![image](https://user-images.githubusercontent.com/61906420/224036738-34f0d260-f58c-42c1-b854-cb0d026fee1c.png)

**Comment by ku-zhen** [comment] 2023-03-09 13:27
> hello，it does‘t work for the .jpg iamge either
> 
> ![image](https://user-images.githubusercontent.com/61906420/224036738-34f0d260-f58c-42c1-b854-cb0d026fee1c.png)

the plugin version 1.0.15

**Comment by ku-zhen** [comment] 2023-03-09 13:36
> hello，it does‘t work for the .jpg iamge either
> 
> ![image](https://user-images.githubusercontent.com/61906420/224036738-34f0d260-f58c-42c1-b854-cb0d026fee1c.png)

oh, I find it may be because of the image's name! After I changed its name, the plugin works!

**Comment by nicojeske** [comment] 2023-03-09 20:08
There was a bug that images in subfolders where not correctly recognized. This should be fixed in 1.0.16 @ku-zhen
