### ISSUE TITLE
Open the article in a new window, the plugin does not work

### ISSUE THREAD

**Issue by jiajiala** [nicojeske/mousewheel-image-zoom#30] opened 2023-08-30 07:56 UTC
When I use the Move to new window command

In the new window, the image can no longer be enlarged or reduced by the scroll wheel

**Comment by jiajiala** [comment] 2023-08-30 07:58
It's the same under canvas

**Comment by Mideks** [comment] 2024-02-26 20:22
Duplicate of #33 and #37. 
#33 is fixed in #40, but #37 still open...

**Comment by nicojeske** [comment] 2024-02-26 20:59
Closed as the main issue is fixed. For progress on the Canvas issue see #37

**Closed by nicojeske** 2024-02-26 20:59 UTC
